name: chnqoo_wallet
description: "Chnqoo wallet."
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  dio: 5.3.2
  # pretty_dio_logger: ^1.3.1
  logger: ^2.0.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  get: ^4.6.6
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  mime: ^1.0.5
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  cached_network_image: ^3.3.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.2.3
  easy_refresh: ^3.3.4
  convex_bottom_bar: ^3.2.0
  # google_mobile_ads: ^5.0.0
  fluent_ui: ^4.8.6
  card_swiper: ^3.0.1
  swipe_cards: ^2.0.0+1
  scrollable_positioned_list: ^0.3.8
  beautiful_soup_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.alpha
    - .env.development
    - .env.production
    - .env.staging
    - assets/
  fonts:
    - family: HarmonyOS
      fonts:
        - asset: fonts/HarmonyOS_Sans_SC_Regular.ttf
        - asset: fonts/HarmonyOS_Sans_SC_Bold.ttf
          weight: 900
        - asset: fonts/HarmonyOS_Sans_SC_Medium.ttf
          weight: 500